### PR TITLE
tags: sort by dotted-decimal version in changelog

### LINKED ISSUE #1471: javascript sort ftw changelog fail
It sorts the older versions wrong

screenshot 2019-03-07 17 11 57

### PR DESCRIPTION
**Pull request by flotwig**
Fixes #1471 

image

### CODE REVIEW

File: lib/tags/changelog.js [hunk 1]
```diff
@@ -7,6 +7,20 @@ const rawRender = require('../raw_render')
 
 const globAsync = Promise.promisify(glob)
 
+const versionNumberSort = (b, a) => {
+  a = path.basename(a).split('.').map((n) => parseInt(n))
```
Comment (brian-mann) [inline lib/tags/changelog.js]: generally best to just use `Number` rather than `parseInt`

```js
path.basename(a).split('.').map(Number)
```

File: lib/tags/changelog.js [hunk 2]
```diff
@@ -18,8 +32,9 @@ module.exports = function changelog (hexo) {
   const pathToChangelogs = path.resolve('source', '_changelogs', '*')
 
   return globAsync(pathToChangelogs)
-  .call('reverse')
   .then((paths) => {
+    paths.sort(versionNumberSort)
```
Comment (brian-mann) [inline lib/tags/changelog.js]: javascript's mutation sort is usually frowned on... prob better to use `_.sortBy`

Comment (flotwig) [reply lib/tags/changelog.js]: `_.sortBy` doesn't let you use an arbitrary function to sort by, but I did update the PR to do `Array.sort` into a new array
