### PR TITLE
fix videos on some browsers

### LINKED ISSUE #612: replace large .gifs with smaller .mp4s
- all `.gif` references now use `.mp4` and the `<video>` tag
- videos are lazy loaded (yalljs)  when users scroll near them, and have placeholder images of de-scaled first frame images
- mp4s are in the "snippets" folder - `./source/img/snippets/*.mp4`, along with corresponding `.png` placeholder image
- mp4s were from existing .gifs, except for the following, which came from source (so the following are high quality): 
    - debugging.mp4
    - installing-cli.mp4
    - installing-global.mp4
    - running-tests.mp4
    - writing-tests.mp4

we should probably work on getting higher quality videos for the others

- add `add-snippet` npm script, to take an existing gif or mp4 and put it in the source properly, it makes a placeholder image and runs it through ffmpeg

### PR DESCRIPTION
**Pull request by Bkucera**
Changed some of the encoding settings
fix #612

### CODE REVIEW

**Comment by brian-mann** [comment]
I'm closing this issue since this PR needs to be done on a new branch / new issue / against `develop`.

Also - the videos here are fine but how did you create them? I don't see any source changes to actually create the videos correctly.

File: cy_scripts/snippet-creator/convert.js [hunk 1]
```diff
@@ -21,34 +23,38 @@ const convert = (inFile, outVid, outImg) => {
...
         return resolve()
       })
-      .on('error', (...args) => ffError(...args, reject))
+      .on('error', ffError(reject))
       .on('progress', (progress) => {
         filesize = progress.targetSize
         spinner.text = `Creating .mp4 - ${filesize}kB`
       })
+
+      onCancel(() => ff.kill())
```
Comment (brian-mann) [inline cy_scripts/snippet-creator/convert.js]: `onCancel(ff.kill)`

**Comment by brian-mann** [comment]
Left one comment, but merging this anyway
